name: server

on:
  push:
    branches:
      - main

env:
  MONGO_URI: mongodb+srv://amantes776:8320QENFGGB@blog.dmcgbjc.mongodb.net/blog?retryWrites=true&w=majority&appName=blog
  JWT_SECRET: 8320QENFGGB

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Deploy to production
        run: |
          ssh user@server 'cd /var/www/mern-app && git pull && npm install && pm2 restart all'